resolver: lts-15.12
packages:
   - uom
extra-deps: [ simple-smt-0.8 ]
build:
  haddock-arguments:
    haddock-args:
    - "--odir=./docs"
    - "--show-all"
    - "--qual=none"
    - "--ignore-all-exports"
    - "--theme=Ocean"
