resolver: lts-15.12
packages:
   - uom
extra-deps:
- simple-smt-0.8
- units-parser-0.1.0.0
build:
  haddock-arguments:
    haddock-args:
    - "--odir=./docs"
    - "--show-all"
    - "--qual=none"
    - "--ignore-all-exports"
