name: cabal

on:
  push:
    branches: [ci-cabal, wip/thoralf-uom]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.0"]
        ghc:
          - "8.4.3"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-haskell@v1
      name: Setup GHC and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: build
      run: |
        # SEE: https://github.com/LeventErkok/sbv/blob/d0931e8305300551992c668468485288cc5bf28c/.travis.yml#L52-L55
        - curl -fsSL https://github.com/Z3Prover/z3/releases/download/Nightly/z3-4.8.9-x64-ubuntu-16.04.zip -o z3-4.8.9-x64-ubuntu-16.04.zip; unzip -j z3-4.8.9-x64-ubuntu-16.04.zip -d z3_downloaded; export PATH=$PATH:$(pwd)/z3_downloaded; z3 --version; fi
        cabal v2-update
        cabal v2-build all --enable-tests

    - name: rows
      run: cabal v2-test rows --test-show-details=direct --test-option="--color=always"

    - name: units
      run: cabal v2-test units --test-show-details=direct --test-option="--color=always"