name: cabal

on:
  push:
    branches: [ci-cabal, wip/thoralf-uom]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.0"]
        ghc:
          - "8.8.3"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-haskell@v1
      name: setup GHC and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - uses: pavpanchekha/setup-z3@v1.2
      name: setup z3
      with:
        version: "4.8.7"

    - name: build
      run: |
        cabal v2-update
        cabal v2-build all --enable-tests

    - name: units
      run: cabal v2-test units --test-show-details=direct --test-option="--color=always"